macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  skip: "changesIncludeOnly('logo/*', '**.md')"
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.0"
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-22.3.0/Contents/Home
    BABASHKA_PLATFORM: macos # used in release script
    BABASHKA_ARCH: aarch64
    BABASHKA_TEST_ENV: native
    BABASHKA_XMX: "-J-Xmx6500m"
    GITHUB_TOKEN: ENCRYPTED[c988eca73b9ce622c262f1dbd01fe31f77de5a438a00643d62fed97dd6221d5c14a37faee3b9d0dbc573efadbc05ec99]
  script: |
    sudo script/install-clojure
    sudo script/install-leiningen
    script/install-graalvm
    export PATH=$GRAALVM_HOME/bin:$PATH
    export JAVA_HOME=$GRAALVM_HOME
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version

    script/compile

    # script/test
    # script/run_lib_tests

    VERSION=$(cat resources/POD_BABASHKA_INSTAPARSE_VERSION)
    arch=${BABASHKA_ARCH:-amd64}
    archive="pod-babashka-instaparse-$VERSION-$BABASHKA_PLATFORM-$arch.zip"
    zip "$archive" pod-babashka-instaparse
    bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dir .
    ./bb release-artifact --file "$archive" || true
  binaries_artifacts:
    path: "pod-babashka-instaparse*.zip"
