#!/usr/bin/env bash

set -eo pipefail

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-instaparse /tmp/release
VERSION=$(cat resources/POD_BABASHKA_INSTAPARSE_VERSION)

pushd /tmp/release

## release binary as zip archive

APP_ARCH=${APP_ARCH:amd64}

zip "pod-babashka-instaparse-$VERSION-$APP_PLATFORM-$APP_ARCH.zip" pod-babashka-instaparse

rm pod-babashka-instaparse

popd

bb release-artifact --file "/tmp/release/pod-babashka-instaparse-$VERSION-$APP_PLATFORM-$APP_ARCH.zip"
