#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-instaparse /tmp/release
VERSION=$(cat resources/POD_BABASHKA_INSTAPARSE_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-instaparse-$VERSION-$APP_PLATFORM-$APP_ARCH.zip" pod-babashka-instaparse

./bb release-artifact --file "pod-babashka-instaparse-$VERSION-$APP_PLATFORM-$APP_ARCH.zip"

## cleanup

rm pod-babashka-instaparse
