#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

clojure -T:build uber

args=(-jar "pod-babashka-instaparse.jar"
      -H:Name=pod-babashka-instaparse
      -H:+ReportExceptionStackTraces
      "--features=clj_easy.graal_build_time.InitClojureClasses"
      --verbose
      --no-fallback
      "-J-Xmx3g"
     )

if [ "$BABASHKA_STATIC" = "true" ] && [ "$BABASHKA_MUSL" = "true" ]; then
    args+=("--static" "--libc=musl"
           # see https://github.com/oracle/graal/issues/3398
           "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"
